[build]
  command = "next build && next export"
  publish = "out"

[build.environment]
  # Optional: Set the Node version if you need a specific one
  NODE_VERSION = "14"

[[plugins]]
  package = "@netlify/plugin-nextjs"
